### ISSUE TITLE
Is there any difference from comake?

### ISSUE THREAD

**Issue by chenkan0104** [baidu/broc#27]
except for git support

**Comment by bdliruihao** [comment]
First, comake2 system get dependency from the scm system and COMAKE file. Broc get dependency only from BROC file.
Second, the final product of comake2 is "Makefile", you need to "make" to get the build product.But broc don't need to get Makefile.

**Comment by chenkan0104** [comment]
Soga!!! These seem to be better choices, but how about the performance of BROC vs to comake or Makefile? If BROC manages dependencies by itself, performance shall be a big problem, and how about parallel compiling, does BROC support it?

**Comment by bdliruihao** [comment]
BROC support parallel compiling and also support incremental compiling.

**Comment by chenkan0104** [comment]
And do you guys have a performance test for BROC?

**Comment by bdliruihao** [comment]
there is some bugs in incremental compiling, it makes BROC cost more time.We will fix  them in the moment.

**Comment by chenkan0104** [comment]
ok.. is it a bug or just a performance issue?

**Comment by bdliruihao** [comment]
a performance issue

**Comment by chenkan0104** [comment]
ok... Hope to see the issue solved.
i'll close this issue first.
